### ISSUE TITLE
User Searches for County Garden to Join

### ISSUE THREAD

**Issue by Lharri11** [nsarzyns/Master-Gardener-Pollinator-Monitoring#22]
1. User logs into pre-exiting account or creates account for use
2. User enters keyword into search bar for wild card search
3. System displays wild card search results
4. User selects desired Garden by name
5. System displays Garden page
6. User selects "Join Group" option
7. System sends notification to Administrative User to approve User's request.

Extensions:
2a. No County Gardens match the keyword entered
   .1: System displays "No results found" message
   .2: User may select "Return to Account" button

**Comment by CrubSkriggle** [comment]
Query method getGardenAddressByGardenName has been added. This method sends a message if no address matches the keyword (Extension 2a).

**Comment by Bagels517** [comment]
done user can use the search bar to query the database for a garden based on a keyword
