### ISSUE TITLE
Import Basic Database Tables

### ISSUE THREAD

**Issue by Lharri11** [nsarzyns/Master-Gardener-Pollinator-Monitoring#27]
Utilize Derby Database in order to populate a basic database with the majority of the necessary tables to represent the Model.

- Create CSV files representing Model classes (County, Garden, Plant, Pollinator, etc.)
- Populate Database by adding CSVs to persistence folder
- Add functions to create necessary tables (County, Garden, Plant, Pollinator, etc.)
- Run Derby Database to create tables

**Comment by Bagels517** [comment]
this is done
